name: guacamol_50k

train:
  path: data/processed/train_50000.csv

validation:
  path: data/processed/val_50000.csv

test:
  path: data/processed/test_50000.csv

smiles_column: smiles

property_columns:
  qed: qed
  logp: logp
  tpsa: tpsa
  sas: sas

max_length: 512