# ==========================================================
# Output
# ==========================================================

output_dir: checkpoints/lora_cfg_10000

# ==========================================================
# Trainer
# ==========================================================

seed: 42

devices: 1                 # Number of GPUs
accelerator: gpu
strategy: ddp

precision: bf16-mixed        # Use "16-mixed" if GPUs don't support BF16

epochs: 1

batch_size: 4
gradient_accumulation_steps: 4

num_workers: 4

# ==========================================================
# Optimization
# ==========================================================

learning_rate: 1e-4

weight_decay: 0.01

warmup_steps: 15

max_grad_norm: 1.0

# ==========================================================
# Logging
# ==========================================================

logging_steps: 10

log_every_n_steps: 10

# ==========================================================
# Checkpointing
# ==========================================================

save_top_k: 3

monitor: val/loss

mode: min

# ==========================================================
# Validation
# ==========================================================

check_val_every_n_epoch: 1

# ==========================================================
# CFG
# ==========================================================

dropout_prob: 0.2

conditioning:
  mode: random